### ISSUE TITLE
Unable to create model instance from database tables

### ISSUE THREAD

**Issue by osieltorres** [oslabs-beta/dORM#29]
I have been trying to export my database structure to model instances as per [documentation](https://github.com/oslabs-beta/dORM#model-instances) and although, I was able to use the init correctly using 
`deno run --allow-read --allow-write --allow-net --unstable https://deno.land/x/dorm/models/init.ts`  
this error appears each time I try to use the model-generator call  
`deno run --allow-read --allow-write --allow-net --unstable https://deno.land/x/dorm/models/model-generator.ts`

```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
const modelQuery = Deno.readTextFileSync(`${__dirname}relationships.sql`);
                        ^
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:42:16)
    at https://deno.land/x/dorm@v1.0.0-beta.7/models/model-generator.ts:13:25
```
Also notice that I had to prefix module URL with `https://` for me to work.

**Comment by m-aung** [comment]
Thank you for submitting the issue @osieltorres .
One of our team members will investigate the error and will post updates on timely basic.

**Comment by m-aung** [comment]
I have some updates on current investigations. @osieltorres 
-filesystem has changed it's usage and no longer support our code.
- found some dependencies are outdated and needs to be update which will effect our current code base.

The new release beta.9 will resolve this issue and I will keep you posted with future updates. 

Thank you for using Dorm.
